# -*- coding: utf-8 -*-
"""toyproject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VBBy_f5JbdQmJ3CDX6ywzHF_1kZ6oL5N
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib as mpl
import matplotlib.pyplot as plt
 
# %config InlineBackend.figure_format = 'retina'
 
!apt -qq -y install fonts-nanum
 
import matplotlib.font_manager as fm
fontpath = '/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf'
font = fm.FontProperties(fname=fontpath, size=9)
plt.rc('font', family='NanumBarunGothic') 
mpl.font_manager._rebuild()

!pip install newspaper3k

import requests
import pandas as pd
from newspaper import Article
from bs4 import BeautifulSoup
import numpy as np # 넘파이
import matplotlib.pyplot as plt # 맷플롯립

df = pd.read_table('goethe_color.csv', sep=',')

df

print(df['reviews'].nunique())

# 중복 샘플 제거
df.drop_duplicates(subset=['reviews'], inplace=True)

df

!pip install konlpy

from konlpy.tag import Okt

tokenizer = Okt()

df['tokenized'] = df['reviews'].apply(tokenizer.nouns)

df

stop_words = ['기자', '제공', '무단', '배포', '무단배포', '배포금지', '이번', '위해', '라며', '금지', '뉴스', '통해', '오늘', '지난달', '지난', '대한', '경우', '관련', '뉴시스', '현재', '지난해', '때문', '지금', '또한', '만큼', '최근', '당시', '올해', '대해', '다시', '모두']

df['tokenized'] = df['tokenized'].apply(lambda x: [item for item in x if item not in stop_words and len(item) > 1])

reviews = np.hstack(df['tokenized'].values)

from collections import Counter

reviews_word_count = Counter(reviews)

print(reviews_word_count)

import numpy as np
from wordcloud import WordCloud

plt.figure(figsize = (15,15))
temp_data = ' '.join(reviews_word_count)
wc = WordCloud(max_words = 2000 , width = 1600 , height = 800, font_path = fontpath).generate(temp_data)
plt.imshow(wc, interpolation = 'bilinear')

